---
template_variables:
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware Tanzu's enterprise-grade software."
  platform_code: PCF
  product_name_lc: pcf

  # VMware Tanzu Variables

  product_full: VMware Tanzuâ„¢ SQL with MySQL for Kubernetes
  product_short: Tanzu MySQL for Kubernetes

  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs

  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI

  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS &#91;Windows&#93;

  segment_runtime_full: Isolation Segment

  ops_manager: Ops Manager

  product_network: VMware Tanzu Network

  # Other variables
  tile_name: VMware Tanzu SQL &#91;MySQL for VMs&#93;
  product_url: https://network.pivotal.io/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/VMware Tanzu-cf">Back to Product Page</a></div>
  service_name: VMware Tanzu SQL &#91;MySQL for VMs&#93;
  service_name_article: VMware Tanzu SQL &#91;MySQL for VMs&#93;
  service_name_article_full: the VMware Tanzu SQL &#91;MySQL for VMs&#93; service
  support_link: <a href="http://support.pivotal.io" target="_blank">Support</a>
  support_call_to_action: <a href="http://support.io" target="_blank">Need Support?</a>
  support_url: http://support.pivotal.io
  path_to_partials: /p-mysql/partials
  single_leader_plan: Multi&#8209;Site Replication
  single_leader_plan_lc: multi&#8209;site replication

  api_version: 235
  gtm_account_id: GTM-MW4LZHR

  use_global_header: true
  global_header_product_href: https://network.pivotal.io/
  global_header_product_link_text: Downloads

  mysql_metrics_origin: /p-mysql
  mysql_metrics_origin_v2: /p.mysql

  current_minor_version: 2.7

  switchboard_url: proxy-BOSH-JOB-INDEX.p-mysql.YOUR-SYSTEM-DOMAIN
